# Generated by Django 3.2 on 2022-11-14 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garpix_user', '0001_initial'),
        ('garpix_favourite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user_session',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='garpix_user.usersession', verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user_session', 'content_type', 'object_id')},
        ),
    ]
